from character_developer_role import CharacterDeveloperRole
from editor_role import EditorRole
from idea_inputer_role import IdeaInputerRole
from plot_generator_role import PlotGeneratorRole
from reader_simulator_role import ReaderSimulatorRole
from writer_role import WriterRole